name: entredos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.0
  url_launcher: ^6.2.6
  open_filex: ^4.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  google_sign_in: ^5.4.4
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.9.2
  file_picker: ^10.2.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.2.3
  intl: 0.20.2
  pdf: ^3.10.1
  image_picker: ^1.0.7
  uuid: ^4.2.0
  share_plus: ^7.2.1
  table_calendar: ^3.0.8
  diacritic: ^0.1.3
  flutter_cached_pdfview: ^0.4.2
  http: ^1.2.1
  fl_chart: ^0.65.0
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.0



  # ğŸ› ï¸ Fork corregido del plugin original
  flutter_downloader: ^1.10.4


fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-Medium.ttf
        weight: 500


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  firebase_auth_platform_interface: 7.2.0